// ห้ามแก้ไขไฟล์นี้โดยตรง
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlTjGkU_Php1jZNipRmlK8wTX1EN-Pl8c',
    appId: '1:948175703284:web:633675becbdb8f1586e2a1',
    messagingSenderId: '948175703284',
    projectId: 'project-14928',
    authDomain: 'project-14928.firebaseapp.com',
    storageBucket: 'project-14928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnr4b55OUl6TfJmPsiprDYEviTTvB9Bs8',
    appId: '1:948175703284:android:ca7adbf948de4b0286e2a1',
    messagingSenderId: '948175703284',
    projectId: 'project-14928',
    storageBucket: 'project-14928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL1FRDXNpHct2fhh4Tk_c8h_D2ZtHrmCY',
    appId: '1:948175703284:ios:561cedaca61f8fb986e2a1',
    messagingSenderId: '948175703284',
    projectId: 'project-14928',
    storageBucket: 'project-14928.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL1FRDXNpHct2fhh4Tk_c8h_D2ZtHrmCY',
    appId: '1:948175703284:ios:561cedaca61f8fb986e2a1',
    messagingSenderId: '948175703284',
    projectId: 'project-14928',
    storageBucket: 'project-14928.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlTjGkU_Php1jZNipRmlK8wTX1EN-Pl8c',
    appId: '1:948175703284:web:2c07a41ceb9dcb8186e2a1',
    messagingSenderId: '948175703284',
    projectId: 'project-14928',
    authDomain: 'project-14928.firebaseapp.com',
    storageBucket: 'project-14928.firebasestorage.app',
  );
}
